### ISSUE TITLE
Example for using dspy from a multi threaded Flask application

### ISSUE THREAD

**Issue by hiradha** [stanfordnlp/dspy#105]
I am trying to use spy from a Flask app server to serve api requests.
However I am getting the below error 

`File "/Users/popurir/nsx-sidekick/sidekick-app/services/vmware/dspy_vaqa_service.py", line 41, in configure_dspy
    dspy.settings.configure(lm=self.lm, rm=self.rm, inherit_config=inherit_config)

  File "/Users/popurir/nsx-sidekick/sidekick-app/venv/lib/python3.11/site-packages/dsp/utils/settings.py", line 70, in configure
    self.__append(config)

  File "/Users/popurir/nsx-sidekick/sidekick-app/venv/lib/python3.11/site-packages/dsp/utils/settings.py", line 54, in __append
    self.stack_by_thread[threading.get_ident()].append(config)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^`

    
Seems to be a case of how dspy.Settings is possibly a singleton per thread and not available across threads?
I do not know multi threading nuances in python enough.
Please provide an example of how to use dspy in multithreaded servers.

**Comment by okhat** [comment]
Is this the full error message

**Comment by hiradha** [comment]
> 

Full stack trace is here . 
```
2023-09-07 09:41:01,102] ERROR in app: Exception on /intelligence/sidekick/prompt [POST]
Traceback (most recent call last):
  File "/Users/popurir/nsx-sidekick/sidekick-app/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/popurir/nsx-sidekick/sidekick-app/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/popurir/nsx-sidekick/sidekick-app/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/popurir/nsx-sidekick/sidekick-app/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/popurir/nsx-sidekick/sidekick-app/server/views.py", line 37, in prompt
    result = facade.prompt(prompt)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/popurir/nsx-sidekick/sidekick-app/server/facade.py", line 42, in prompt
    return prompt_router.get_tool(prompt).evaluate(prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/popurir/nsx-sidekick/sidekick-app/prompt/tool/vmware_doc_tool.py", line 23, in evaluate
    response_text = self._vaqa_service.retreive_llm_read(prompt)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/popurir/nsx-sidekick/sidekick-app/services/vmware/dspy_vaqa_service.py", line 80, in retreive_llm_read
    self.configure_dspy(False)
  File "/Users/popurir/nsx-sidekick/sidekick-app/services/vmware/dspy_vaqa_service.py", line 41, in configure_dspy
    dspy.settings.configure(lm=self.lm, rm=self.rm, inherit_config=inherit_config)
  File "/Users/popurir/nsx-sidekick/sidekick-app/venv/lib/python3.11/site-packages/dsp/utils/settings.py", line 70, in configure
    self.__append(config)
  File "/Users/popurir/nsx-sidekick/sidekick-app/venv/lib/python3.11/site-packages/dsp/utils/settings.py", line 54, in __append
    self.stack_by_thread[threading.get_ident()].append(config)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 123145459998720
127.0.0.1 - - [07/Sep/2023 09:41:01] "POST /intelligence/sidekick/prompt HTTP/1.1" 
```
My service is initialized  as below

```
def __init__(self, inherit_config:bool = True):
        self.lm = dspy.OpenAI(
            model=Config.MODEL_NAME,
            max_tokens=1024,
            api_key=Config.OPENAI_API_KEY,
            api_base=Config.OPENAI_API_BASE
        )
        self.rm = vAQA() # Our RM implementation
        dspy.settings.configure(lm=self.lm, rm=self.rm, inherit_config=inherit_config)
        train = [
            {
                'question': 'xxxxx?',
                'answer': 'yyyy'
            },
            {
                'question': 'aaa',
                'answer': 'bbb'
            },
        ]
        # Append Llama2 tags
        train = [{'question': f"{x['question']}[/INST]", 'answer': f"{x['answer']}</s>"} for x in train]
        # Create training examples
        trainset = [dspy.Example(x).with_inputs('question') for x in train]
        from dspy.teleprompt import LabeledFewShot
        # Set up a basic teleprompter, which will compile our RAG program with a few examples
        self.teleprompter = LabeledFewShot(k=4)
        # Compile!
        self.compiled_rag = self.teleprompter.compile(RAG(), trainset=trainset)
```
# Flask thread calls below method
```
def retreive_llm_read(self, prompt:str):
        # self.configure_dspy(False)
        # Get the answer using the compiled RAG LabeledFewShot Teleprompter
        #pred = compiled_rag(question="how do i configure multiple culsters in tanzu?")
        pred = self.compiled_rag(question=prompt)
        print(pred.answer)
        # Inspect the prompt
        self.lm.inspect_history(n=1)
       return pred.asnwer
```

I tried calling configure_dspy within flask thread and also during service initialization but both approaches did not work. I also tried to set inherit config to false and that also did not work. Primarily I think it is because of the threaded->stack dictionary in dsp.settings.

**Comment by okhat** [comment]
Ok let me look into this — seems easy to fix. 

but any chance it will work directly with fastapi?

**Comment by okhat** [comment]
i think fastapi isn’t multi threaded by default?

**Comment by hiradha** [comment]
> i think fastapi isn’t multi threaded by default?

I do not have much understanding. Our server is already flask based - so not easy to switch at this point.

**Comment by hiradha** [comment]
> Ok let me look into this — seems easy to fix.
> 
> but any chance it will work directly with fastapi?

@okhat  Can you provide some guidance on where code should be changed to fix this? I am not sure what should be done to fix this.

**Comment by okhat** [comment]
Do you mind sharing minimal skeleton of code I can test it with?

**Comment by okhat** [comment]
I will try to fix this today!

**Comment by hiradha** [comment]
> Do you mind sharing minimal skeleton of code I can test it with?

I cannot share the code we have but any simple hello world flask application will do
https://github.com/Sysnove/flask-hello-world 
https://www.geeksforgeeks.org/how-to-write-a-simple-flask-api-for-hello-world/

**Comment by hasalams** [comment]
I too get a similar `KeyError` when using DSPy with the FastAPI application. 

```python
    dspy.settings.configure(lm=lm, rm=rm)
    │    │        │            │      └ <app.engines.dsp_engine.dsp_rm.DSPRM object at 0x7f968ab69690>
    │    │        │            └ <app.engines.dsp_engine.dsp_lm.DSPLM object at 0x7f968ab69810>
    │    │        └ <function Settings.configure at 0x7f96a448cdc0>
    │    └ {'lm': None, 'rm': None, 'branch_idx': 0, 'reranker': None, 'compiled_lm': None, 'force_reuse_cached_compilation': False, 'co...
    └ <module 'dspy' from '/home/hasala/sprint2/llm-api/env/lib/python3.10/site-packages/dspy/__init__.py'>

  File "/home/hasala/sprint2/llm-api/env/lib/python3.10/site-packages/dsp/utils/settings.py", line 66, in configure
    config = {**self.config, **kwargs}
                │    │         └ {'lm': <app.engines.dsp_engine.dsp_lm.DSPLM object at 0x7f968ab69810>, 'rm': <app.engines.dsp_engine.dsp_rm.DSPRM object at 0...
                │    └ <property object at 0x7f96a445c590>
                └ {'lm': None, 'rm': None, 'branch_idx': 0, 'reranker': None, 'compiled_lm': None, 'force_reuse_cached_compilation': False, 'co...
  File "/home/hasala/sprint2/llm-api/env/lib/python3.10/site-packages/dsp/utils/settings.py", line 42, in config
    return self.stack_by_thread[threading.get_ident()][-1]
           │    │               │         └ <built-in function get_ident>
           │    │               └ <module 'threading' from '/usr/lib/python3.10/threading.py'>
           │    └ {140285253013952: [{'lm': None, 'rm': None, 'branch_idx': 0, 'reranker': None, 'compiled_lm': None, 'force_reuse_cached_compi...
           └ {'lm': None, 'rm': None, 'branch_idx': 0, 'reranker': None, 'compiled_lm': None, 'force_reuse_cached_compilation': False, 'co...

KeyError: 140284490921536
```

**Comment by arnavsinghvi11** [comment]
Hi @hiradha  and @hasalams ,

I have an in-progress PR that may provide a potential solution for this issue. Please let me know if this helps and any other updates!

Thanks, 
Arnav Singhvi

**Comment by okhat** [comment]
Seems OK? Closing.
