### ISSUE TITLE
AssertionError in Trial, failed with value None: `assert max_depth > 0`

### ISSUE THREAD

**Issue by rawsh-rubrik** [stanfordnlp/dspy#1252]
Seems like this assertion is failing sporadically with AzureOpenAIClient
```
[W 2024-07-05 03:51:26,977] Trial 13 failed with value None.
Traceback (most recent call last):
  File "/Users/robert/fact_eval/questions_dspy.py", line 134, in <module>
    compiled_program = teleprompter.compile(program, trainset=train, valset=val, num_batches=batches, max_bootstrapped_demos=5, max_labeled_demos=2, eval_kwargs=eval_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dspy/teleprompt/mipro_optimizer_v2.py", line 489, in compile
    score = study.optimize(objective_function, n_trials=num_batches)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/optuna/study/_optimize.py", line 62, in _optimize
    _optimize_sequential(
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/optuna/study/_optimize.py", line 159, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/optuna/study/_optimize.py", line 247, in _run_trial
    raise func_err
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dspy/teleprompt/mipro_optimizer_v2.py", line 391, in objective
    score = eval_candidate_program(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dspy/teleprompt/utils.py", line 50, in eval_candidate_program
    score = evaluate(
            ^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dspy/evaluate/evaluate.py", line 193, in __call__
    reordered_devset, ncorrect, ntotal = self._execute_multi_thread(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dspy/evaluate/evaluate.py", line 110, in _execute_multi_thread
    example_idx, example, prediction, score = future.result()
                                              ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dspy/evaluate/evaluate.py", line 103, in cancellable_wrapped_program
    return wrapped_program(idx, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dspy/evaluate/evaluate.py", line 178, in wrapped_program
    raise e
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dspy/evaluate/evaluate.py", line 160, in wrapped_program
    prediction = program(**example.inputs())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dspy/primitives/program.py", line 26, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dspy/primitives/assertions.py", line 294, in forward
    return wrapped_forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dspy/primitives/assertions.py", line 220, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/fact_eval/questions_dspy.py", line 72, in forward
    res = self.generate_question(context=context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dspy/predict/retry.py", line 64, in __call__
    pred = self.module(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dspy/predict/predict.py", line 61, in __call__
    return self.forward(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dspy/predict/chain_of_thought.py", line 59, in forward
    return super().forward(signature=signature, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dspy/predict/predict.py", line 103, in forward
    x, C = dsp.generate(template, **config)(x, stage=self.stage)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dsp/primitives/predict.py", line 111, in do_generate
    return generate(template, **new_kwargs)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dsp/primitives/predict.py", line 111, in do_generate
    return generate(template, **new_kwargs)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/Library/Caches/pypoetry/virtualenvs/fact-eval-xlj0d7D7-py3.12/lib/python3.12/site-packages/dsp/primitives/predict.py", line 110, in do_generate
    assert max_depth > 0
           ^^^^^^^^^^^^^
AssertionError
```

code:

```python
prompt_model = dspy.AzureOpenAI()
task_model = dspy.AzureOpenAI()

class ReturnGeneratedQuestion(dspy.Signature):
    """Generates factual question and short answer pair from a given context."""
    context = dspy.InputField(description="The context to generate question and answer pair from.")
    question = dspy.OutputField(description="The generated question.")
    answer = dspy.OutputField(description="The short answer to the generated question.")

class GenerateQuestion(dspy.Module):
    def __init__(self):
        super().__init__()
        self.generate_question = dspy.ChainOfThought(ReturnGeneratedQuestion)
        
    def forward(self, context):
        res = self.generate_question(context=context)
        question = res.question
        answer = res.answer

        dspy.Suggest(
            len(answer) <= 100,
            "Answer should be short and less than 100 characters",
        )
        return dspy.Prediction(question=question, answer=answer)

program = GenerateQuestion().activate_assertions()

def validate_context_question_answer(example, pred, trace=None):
    # run nli model to get a score 0-1
    if trace is not None:
        if score <= 0.99:
            print(f"[{id}] rejected question: {pred.question}")
        else:
            print(f"[{id}] accepted question: {pred.question}")
        # compiling
        return score > 0.99
    return score

# Define hyperparameters:
N = 10 # The number of instructions and fewshot examples that we will generate and optimize over
batches = 30 # The number of optimization trials to be run (we will test out a new combination of instructions and fewshot examples in each trial)
temperature = 1.0 # The temperature configured for generating new instructions

# Compile
eval_kwargs = dict(num_threads=8, display_progress=True, display_table=5)
teleprompter = MIPROv2(prompt_model=task_model, task_model=prompt_model, metric=validate_context_question_answer, num_candidates=N, init_temperature=temperature, verbose=True)
compiled_program = teleprompter.compile(program, trainset=train, valset=val, num_batches=batches, max_bootstrapped_demos=5, max_labeled_demos=2, eval_kwargs=eval_kwargs)
compiled_program.save("compiled.dspy")
```

**Comment by okhat** [comment]
Should be ok in 2.5 if you migrate
