### ISSUE TITLE
Got no module "dspy.teleprompt" even after installing dspy-ai

### ISSUE THREAD

**Issue by albertlieyingadrian** [stanfordnlp/dspy#1494]
I tried importing dspy.teleprompt but I kept getting this error
```shell
Traceback (most recent call last):
  File "/Users/albertlieadrian/Documents/Random/ai-llm-playground/evals/dspy.py", line 2, in <module>
    import dspy
  File "/Users/albertlieadrian/Documents/Random/ai-llm-playground/evals/dspy.py", line 3, in <module>
    from dspy.teleprompt import MIPROv2 as MIPRO
ModuleNotFoundError: No module named 'dspy.teleprompt'; 'dspy' is not a package
```

even though I have install the right dspy module. My command
```shell
pip install dspy-ai
```

My code:
```python
from datasets import load_dataset
import dspy
from dspy.teleprompt import MIPROv2 as MIPRO
from dspy.functional import TypedPredictor
from dspy.evaluate.evaluate import Evaluate
import os
from dotenv import load_dotenv

load_dotenv()

llm = dspy.OpenAI(
    model='gpt-4o',
    api_key=os.environ['OPENAI_API_KEY']
)

dspy.settings.configure(lm=llm)

```

Python version: Python 3.12.4

Any extra setup I need to do here?

**Comment by albertlieyingadrian** [comment]
Found the bug. It was because my file's name is`dspy.py`
