### ISSUE TITLE
ValueError: Expected dict_keys(['answer']) but got dict_keys([])

### ISSUE THREAD

**Issue by rangehow** [stanfordnlp/dspy#1539]
I run the official code example in `intro.ipynb`：
```python
import dspy

lm = dspy.LM(model='openai/default', api_key=" ", api_base=" ",temperature=0.9, max_tokens=3000,)
colbertv2_wiki17_abstracts = dspy.ColBERTv2(url='http://20.102.90.50:2017/wiki17_abstracts')

dspy.settings.configure(lm=lm, rm=colbertv2_wiki17_abstracts)

from dspy.datasets import HotPotQA

# Load the dataset.
dataset = HotPotQA(train_seed=1, train_size=20, eval_seed=2023, dev_size=50, test_size=0)

# Tell DSPy that the 'question' field is the input. Any other fields are labels and/or metadata.
trainset = [x.with_inputs('question') for x in dataset.train]
devset = [x.with_inputs('question') for x in dataset.dev]

len(trainset), len(devset)

train_example = trainset[0]
print(f"Question: {train_example.question}")
print(f"Answer: {train_example.answer}")

dev_example = devset[18]
print(f"Question: {dev_example.question}")
print(f"Answer: {dev_example.answer}")
print(f"Relevant Wikipedia Titles: {dev_example.gold_titles}")


class BasicQA(dspy.Signature):
    """Answer questions with short factoid answers."""

    question = dspy.InputField()
    answer = dspy.OutputField(desc="often between 1 and 5 words")
    
# Define the predictor.
generate_answer = dspy.Predict(BasicQA)

# Call the predictor on a particular input.
pred = generate_answer(question=dev_example.question)

# Print the input and the prediction.
print(f"Question: {dev_example.question}")
print(f"Predicted Answer: {pred.answer}")

```

ERROR I get
```bash
Traceback (most recent call last):
  File "/mnt/rangehow/dspy/1.py", line 39, in <module>
    pred = generate_answer(question=dev_example.question)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/rangehow/dspy/dspy/predict/predict.py", line 98, in __call__
    return self.forward(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/rangehow/dspy/dspy/predict/predict.py", line 131, in forward
    completions = v2_5_generate(lm, config, signature, demos, kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/rangehow/dspy/dspy/predict/predict.py", line 231, in v2_5_generate
    return adapter(lm, lm_kwargs=lm_kwargs, signature=signature, demos=demos, inputs=inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/rangehow/dspy/dspy/adapters/base.py", line 11, in __call__
    value = self.parse(signature, output)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/rangehow/dspy/dspy/adapters/chat_adapter.py", line 58, in parse
    raise ValueError(f"Expected {signature.output_fields.keys()} but got {fields.keys()}")
ValueError: Expected dict_keys(['answer']) but got dict_keys([])
```

The outputs from LLM, I print it out:
```
['answer: American\n[[ ## completed ## ]]']
```

**Comment by rangehow** [comment]
https://github.com/stanfordnlp/dspy/blob/cc96b7a61375ebddc9896245e10b96cb49e2e27c/dspy/adapters/chat_adapter.py#L47
`[(None, 'answer: American'), ('completed', '')]`

**Comment by apohllo** [comment]
I attach to the same issue, since the message is the same, but the scenario is different. 
This massage occurs when running COPRO optimizer. The problem is that it the model might exceed the prompt output limit, and the instruction is too long and does not include the expected sections.

I would recommend to include a logic in the optimizer that will ignore the output/generations that don't include the necessary fields rather than fail the whole optimization. This should be a very basic improvement.

**Comment by okhat** [comment]
Hey @rangehow ! Thanks for opening this.

What is `openai/default`? What LM is this connecting to? It seems like that LM fails to respect the output format, but I can look more closely if I know more.

**Comment by rangehow** [comment]
> Hey @rangehow ! Thanks for opening this.嘿 ！感谢您打开这个。
> 
> What is `openai/default`? What LM is this connecting to? It seems like that LM fails to respect the output format, but I can look more closely if I know more.什么是`openai/default` ？这是连接到哪个LM？看起来 LM 不尊重输出格式，但如果我了解更多，我可以更仔细地观察。

Thanks for your reply, I use Qwen2.5-7B-instruct hosted by sglang

**Comment by apohllo** [comment]
In my case it's speakleash/Bielik-11B-v2.2-Instruct-GPTQ and the model is not producing correct output - the markers are missing in the output of the model.

**Comment by okhat** [comment]
Ah, thank you both! OK it seems like these models don't stick to the format described in the instructions too well.

One thing that may help is using a larger LM (like gpt-4o-mini) to teach the small LM by showing it examples. This can be super cheap because the larger LM is only invoked very few times.

Learn more about this: https://github.com/stanfordnlp/dspy/blob/main/examples/nli/scone/scone.ipynb

That said, I will look into this class of models and try to see how we can ensure they're supported out of the box.

**Comment by apohllo** [comment]
I think a nice addition that could work is auto-fixing the output by the model itself. I.e. if the field is wrongly structured ask the model to fix it. This should be straight forward to implement.

**Comment by NumberChiffre** [comment]
@rangehow did you notice this with v2.4.16 or v2.4.17? I've upgraded to 2.5.2 and 2.5.3 and am noticing the same issue with `qwen-7b` with ollama.

**Comment by okhat** [comment]
Tagging @isaacbmiller since he's exploring this sort of thing nowadays.

**Comment by isaacbmiller** [comment]
@okhat should predictors include retries by default?

I think the formatting change to the system prompt we were talking about will help with outputting `[ ## answer ## ]` instead of `answer:`

**Comment by cielonet** [comment]
Hello, I am using Phi-3-mini-128k-instruct and ran into the say problem as previously described. :-/ If there is anything I could do to help test possible solutions please let me know. I'm using the 'new' adapter (dspy.LM) through an Open AI-compaitble server (e.i. text-generation-inference). Thank you.

**Comment by isaacbmiller** [comment]
@cielonet if you could try pointing to the `mm-adapter` branch and letting me know if the problem still occurs that would be extremely helpful.

If not I can try it myself sometime tomorrow.

**Comment by cielonet** [comment]
> @cielonet if you could try pointing to the `mm-adapter` branch and letting me know if the problem still occurs that would be extremely helpful.
> 
> If not I can try it myself sometime tomorrow.

Will do this now! I should get back to you shortly! Thank you. :-) :+1:

**Comment by cielonet** [comment]
Hey, @isaacbmiller, I tried your changes and I'm still getting same issue, however I noticed this code change does show me by default the llm response. I have attached an output. Generally I would do this in notebook, but I am testing DSPy with airflow, so the outputs below show the results of an execution of a task. I have attached the provided code as well for ref.

```bash
01:47:25 - LiteLLM:INFO: utils.py:2983 - 
LiteLLM completion() model= tgi; provider = openai
[2024-10-05T01:47:25.797+0000] {utils.py:2983} INFO - 
LiteLLM completion() model= tgi; provider = openai
[2024-10-05T01:47:26.830+0000] {_client.py:1026} INFO - HTTP Request: POST http://192.168.1.152:8085/v1/chat/completions "HTTP/1.1 200 OK"
01:47:26 - LiteLLM:INFO: utils.py:999 - Wrapper: Completed Call, calling success_handler
[2024-10-05T01:47:26.839+0000] {utils.py:999} INFO - Wrapper: Completed Call, calling success_handler
Expected dict_keys(['reasoning', 'output']) but got dict_keys([]) from [[reasoning]] 9.9 is larger than 9.11 because when comparing decimal numbers, the number with the greater value in the tenths place and beyond is the larger number. Here, both numbers have "9" in the ones place, but in the tenths place, 9.9 has a "9" compared to 9.11 which has a "1". Additionally, 9.9 has a "9" in the hundredths place, whereas 9.11 has a "1" in the hundredths place, further confirming that 9.9 is larger.

[[output]] 9.9

[[completed]]
2024-10-05 01:47:26,844] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/includes/lib/extract/calls.py", line 356, in use_cot
    response = qa(input=question)
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/dspy/primitives/program.py", line 26, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/dspy/predict/chain_of_thought.py", line 44, in forward
    return self._predict(signature=signature, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/dspy/predict/predict.py", line 106, in __call__
    return self.forward(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/dspy/predict/predict.py", line 139, in forward
    completions = v2_5_generate(lm, config, signature, demos, kwargs, _parse_values=self._parse_values)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/dspy/predict/predict.py", line 245, in v2_5_generate
    return adapter(lm, lm_kwargs=lm_kwargs, signature=signature, demos=demos, inputs=inputs, _parse_values=_parse_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/dspy/adapters/base.py", line 30, in __call__
    value = self.parse(signature, output, _parse_values=_parse_values)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/dspy/adapters/chat_adapter.py", line 66, in parse
    raise ValueError(f"Expected {signature.output_fields.keys()} but got {fields.keys()}")
ValueError: Expected dict_keys(['reasoning', 'output']) but got dict_keys([])

```

```python
import litellm
import dspy
litellm.caching = False
litellm.telemetry = False


llm = dspy.LM(model=MODEL, api_base=BASE_URL, api_key=API_KEY, temperature=1.0, cache=False, model_type='chat')
dspy.configure(lm=llm)
dspy.settings.experimental = True

@task
def use_cot(query: list[dict[str,str]]) -> str:
    
    # Extract 'content' from each dictionary in the list
    question = '\n'.join(item['content'] for item in query) # query = [{'role': 'user', 'content': 'What number is larger 9.11 or 9.9?'}] -> 'What number is larger 9.11 or 9.9?\n'

    qa = dspy.ChainOfThought('input -> reasoning, output')
    response = qa(input=question)
    print(f"RESPONSE: {response}")
    
    return "Done" # temp holder until we can fix issue!
```

**Installation Procedure**
```bash
pip3 install git+https://github.com/stanfordnlp/dspy.git@mm-adapter
```

**Note**
I didn't include it here but I tested with the dspy.Retry module using try:except and I still get a ValueError with output shown.

**Comment by isaacbmiller** [comment]
Sweet thanks for sending this. Will look more into it tomorrow

**Comment by cielonet** [comment]
> Sweet thanks for sending this. Will look more into it tomorrow

Hey there, Just wanted to see if there were any new updates on this issue? If there is anything I can do to assist with testing, etc., please let me know. Thank you.

**Comment by NumberChiffre** [comment]
I ran my code with v2.5.6 on Python 3.12 and am still getting similar error as the author:
https://github.com/NumberChiffre/mcts-llm/blob/main/notebooks/evaluate.ipynb

^All good with 2.4.17, swapped to 2.5.6 to get the following with the `evaluate(ZeroShotCoT())`:
```shell
Average Metric: 14 [/](https://file+.vscode-resource.vscode-cdn.net/) 23  (60.9):  64%|██████▍   | 23/36 [00:17<00:11,  1.09it/s] ERROR:dspy.evaluate.evaluate:2024-10-11T05:26:41.462176Z [error    ] Error for example in dev set: 		 Expected dict_keys(['reasoning', 'answer']) but got dict_keys(['reasoning']). Set `provide_traceback=True` to see the stack trace. [dspy.evaluate.evaluate] filename=evaluate.py lineno=198
Average Metric: 19.0 [/](https://file+.vscode-resource.vscode-cdn.net/) 35  (54.3):  97%|█████████▋| 35/36 [00:46<00:02,  2.21s/it]ERROR:dspy.evaluate.evaluate:2024-10-11T05:27:25.933474Z [error    ] Error for example in dev set: 		 Expected dict_keys(['reasoning', 'answer']) but got dict_keys(['reasoning']). Set `provide_traceback=True` to see the stack trace. [dspy.evaluate.evaluate] filename=evaluate.py lineno=198
Average Metric: 19.0 [/](https://file+.vscode-resource.vscode-cdn.net/) 36  (52.8): 100%|██████████| 36/36 [01:04<00:00,  1.79s/it]
```

**Comment by cielonet** [comment]
Just a quick update. I retested this morning with the latest version of dspy==2.5.9 and the problem seems to go away. I will continue to do more testing.

**Comment by NumberChiffre** [comment]
> Just a quick update. I re-tested this morning with the latest version of dspy==2.5.9 and the problem seems to have gone away. I will continue to do more testing. Perhaps #1630 fixed the issue?!
> 
> Also another change I made was now I am using vllm as opposed to tgi as the backend with phi3.5-mini. Not sure if this was the issue?

Thanks for the update. I'm running with 2.5.6 and even tried with `qwen2.5:14b-instruct` with the same issue. I've managed to get around this problem by adding docstring to one of my `dspy.Signature` that caused this problem, and am able to run MIPROv2 without any errors. Turns out not having any docstring for `dspy.Signature` was a problem when using with `litellm`.

**Comment by chansonZ** [comment]
- still getting similar error as the author on latest v2.5.10 on Python 3.10.
- code copy from : https://dspy-docs.vercel.app/docs/deep-dive/optimizers/miprov2

**Comment by isaacbmiller** [comment]
We are working on a larger scale workaround for issues like this.

For now, expect that the 2.5 predictors will error more loudly than before. Depending on how large of an LLM i am using, I temper my expectations of how well it can follow the required format.

There are two possible things I do here:
1. pass max_errors=10000 to your optimizer or evaluation function. The performance should still equal or outperform pre-2.5.
2. Few shot examples really help small models understand the format. E.g. Llama 3.2 1B struggles with the format (~2%) but when shown few shot examples it understands the format much better.

**Comment by Harrolee** [comment]
datapoint: dolphin-llama3 struggles with the output format and throws the ValueError as well.

**Comment by cielonet** [comment]
Just confirmed this issue is still a problem with phi3.5. :-(

**Comment by satriowputra** [comment]
I got the same issue with GPT-3.5-Turbo-0125. The issue was resolved by increasing `max_token` when initializing `dspy.LM` object

**Comment by paulacanva** [comment]
Following as I'm having the same issue, using gpt-4o-mini.

```
ValueError: Expected dict_keys(['advice', 'categories']) but got dict_keys(['advice'])
Average Metric: 66.34999999999998 / 184  (36.1):  62%|██████▏   | 184/299 [00:19<00:12,  9.27it/s] 
```

**Comment by okhat** [comment]
Hey everyone, can you:

1. Upgrade to DSPy latest, i.e. v2.5.18
2. Use `dspy.Predict` or `dspy.ChainOfThought` instead of `dspy.TypedPredictor`.
3. Let me know here if the issue is not solved.

I think things are better now for most models.

**Comment by cielonet** [comment]
So I did some testing on v2.5.18 with ms phi3.5 and found something interesting. 

When my code looks like this -> ```qa = dspy.ChainOfThought('input -> reasoning, output')``` I always get an error
`ValueError: Expected dict_keys(['reasoning', 'output']) but got dict_keys(['reasoning'])`

But when I add just a `single space` to the end of the parameter in the ChainOfThought function like this `qa = dspy.ChainOfThought('input -> reasoning, output ')`

I always get a solid response back!
```bash
RESPONSE: Prediction(
    reasoning="To determine which number is larger, we compare the numbers digit by digit starting from the leftmost (highest value) digit. Both numbers have '9' in the ones place, so we move to the next digit to the right, which is the tenths place. In 9.11, the tenths digit is '1', and in 9.9, the tenths digit is '9'. Since '9' is larger than '1', we can conclude that 9.9 is larger than 9.11 without needing to compare further digits.",
    output='9.9'
)```

**Comment by paulacanva** [comment]
As per another [example](https://github.com/stanfordnlp/dspy/issues/1717) provided by @okhat, adding type hints seems to have solved the issue for me. It might be worth updating docs (such as [this](https://dspy-docs.vercel.app/building-blocks/5-metrics/?h=trace#advanced-accessing-the-trace)) to make clear that DSPy leverages such kind of information.

**Comment by rahmed12** [comment]
I'm just adding my two cents here.  I was getting the similar error above when using ollama and mistral-nemo:12b-instruct-2407-q8_0 (i'm not adding most of my code ) :

`
mistral_nemo = ollama_llm_client("mistral-nemo:12b-instruct-2407-q8_0")

dspy.ChainOfThought(ParsePassage)

class ParsePassage(dspy.Signature):
    """ You are a English professor  """

    narration = dspy.InputField(desc='Text from a student')
    answer = dspy.OutputField(desc="""Output must  be in Json array in the format """
`

Error:
`    raise ValueError(f"Expected {signature.output_fields.keys()} but got {fields.keys()}")
ValueError: Expected dict_keys(['reasoning', 'answer']) but got dict_keys([])`


When I changed
`answer = dspy.OutputField(desc="""Output must  be in Json array in the format """`

to:
`answer: **dict** = dspy.OutputField(desc="""Output must  be in Json array in the format """`

The error  went away.  I hope this helps someone

**Comment by jpmalone0** [comment]
> Hey everyone, can you:
> 
>     1. Upgrade to DSPy latest, i.e. v2.5.18
> 
>     2. Use `dspy.Predict` or `dspy.ChainOfThought` instead of `dspy.TypedPredictor`.
> 
>     3. Let me know here if the issue is not solved.
> 
> 
> I think things are better now for most models.

Can confirm I get the issue on dspy.ChainOfThought

**Comment by falmanna** [comment]
This happen with any model that doesn't perform well with structured output.

**Comment by NumberChiffre** [comment]
`llama3.1` is pretty good with structured output so far, except...
```python
ValueError: Expected dict_keys(['reasoning', 'feedback', 'confidence']) but got dict_keys([])
```

Is there a plan for a permanent fix on this issue? It's almost 2 months :(

**Comment by dvs23** [comment]
Any news on this? I still have this problem with DSPy 2.6.2 and primarily phi4 (although every model can in principle fail to generate the correct output format, of course).

I think this is something that should be covered by the max_errors parameter, as currently a single failure of a model to provide correctly structured outputs at that point crashed the whole MIPROv2 optimization for me:

```python
Traceback (most recent call last):
  File "/some/path/venv/lib/python3.10/site-packages/dspy/adapters/base.py", line 30, in __call__
    value = self.parse(signature, output)
  File "/some/path/venv/lib/python3.10/site-packages/dspy/utils/callback.py", line 234, in wrapper
    return fn(instance, *args, **kwargs)
  File "/some/path/venv/lib/python3.10/site-packages/dspy/adapters/chat_adapter.py", line 86, in parse
    raise ValueError(f"Expected {signature.output_fields.keys()} but got {fields.keys()}")
ValueError: Expected dict_keys(['proposed_instruction']) but got dict_keys([])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/some/path/src/llm/compositionality/fewshot.py", line 296, in fewshot_mipro
    optimized_program = teleprompter.compile(
  File "/some/path/venv/lib/python3.10/site-packages/dspy/teleprompt/mipro_optimizer_v2.py", line 173, in compile
    instruction_candidates = self._propose_instructions(
  File "/some/path/venv/lib/python3.10/site-packages/dspy/teleprompt/mipro_optimizer_v2.py", line 451, in _propose_instructions
    instruction_candidates = proposer.propose_instructions_for_program(
  File "/some/path/venv/lib/python3.10/site-packages/dspy/propose/grounded_proposer.py", line 358, in propose_instructions_for_program
    self.propose_instruction_for_predictor(
  File "/some/path/venv/lib/python3.10/site-packages/dspy/propose/grounded_proposer.py", line 410, in propose_instruction_for_predictor
    proposed_instruction = instruction_generator.forward(
  File "/some/path/venv/lib/python3.10/site-packages/dspy/propose/grounded_proposer.py", line 246, in forward
    instruct = self.generate_module_instruction(
  File "/some/path/venv/lib/python3.10/site-packages/dspy/utils/callback.py", line 234, in wrapper
    return fn(instance, *args, **kwargs)
  File "/some/path/venv/lib/python3.10/site-packages/dspy/predict/predict.py", line 67, in __call__
    return self.forward(**kwargs)
  File "/some/path/venv/lib/python3.10/site-packages/dspy/predict/predict.py", line 97, in forward
    completions = adapter(lm, lm_kwargs=config, signature=signature, demos=demos, inputs=kwargs)
  File "/some/path/venv/lib/python3.10/site-packages/dspy/adapters/base.py", line 45, in __call__
    return JSONAdapter()(lm, lm_kwargs, signature, demos, inputs)
  File "/some/path/venv/lib/python3.10/site-packages/dspy/adapters/json_adapter.py", line 61, in __call__
    value = self.parse(signature, output)
  File "/some/path/venv/lib/python3.10/site-packages/dspy/utils/callback.py", line 234, in wrapper
    return fn(instance, *args, **kwargs)
  File "/some/path/venv/lib/python3.10/site-packages/dspy/adapters/json_adapter.py", line 95, in parse
    fields = {k: v for k, v in fields.items() if k in signature.output_fields}
AttributeError: 'list' object has no attribute 'items'
```

At the same time, I feel like this is something that should be handled using (grammar-)constrained decoding (see [1,2], repos: [3,4]), as the expected output structure and especially JSON is relatively well-defined. I could maybe help with that, we ([2, 4]) already did some things with GCD in the past.

I know this is not feasible in every environment, as you need logit-level access to the LM output, but in some it should be possible. For example, llama.cpp even supports grammar-constrained decoding already [5] and Ollama is apparently working on support for returning logits/logprobs via the API as well [6]. Maybe one could also leverage the already-existing DSPy Assertions for this?

[1] [https://doi.org/10.18653/v1/2023.emnlp-main.674](https://doi.org/10.18653/v1/2023.emnlp-main.674)
[2] [https://doi.org/10.3389/frai.2024.1406857](https://doi.org/10.3389/frai.2024.1406857)
[3] [https://github.com/epfl-dlab/transformers-CFG](https://github.com/epfl-dlab/transformers-CFG)
[4] [https://github.com/ag-sc/Clinical-Trial-IE-GCD](https://github.com/ag-sc/Clinical-Trial-IE-GCD)
[5] [https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md](https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md)
[6] [https://github.com/ollama/ollama/issues/2415](https://github.com/ollama/ollama/issues/2415)

**Comment by nickdickinson** [comment]
Maybe as a first step it is just to create a custom `GeneratedFormatException` or something similar? This could then be handled appropriately during evaluation and/or optimization and that handling could be added incrementally as people have time to address this in each part of DSPy. Additionally, adding some more types of constraints on generation where possible is also interested (structured responses).

**Comment by binzhango** [comment]
I got same issue when using `llama3` and `phi4` in ollama, but it's working well in `gemma3`.
