### ISSUE TITLE
PgVectorRM: dspy 2.5.6 does not provide the extra 'pgvector'

### ISSUE THREAD

**Issue by excubo-jg** [stanfordnlp/dspy#1607]
```
import dspy
from dspy.retrieve.pgvector_rm import PgVectorRM
```
causes this error message when executing:

```
  File "/lib/python3.11/site-packages/dspy/retrieve/pgvector_rm.py", line 7, in <module>
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Ubuntu/postgres.py", line 2, in <module>
    from dspy.retrieve.pgvector_rm import PgVectorRM
  File "/lib/python3.11/site-packages/dspy/retrieve/pgvector_rm.py", line 11, in <module>
    raise ImportError(
ImportError: The 'pgvector' extra is required to use PgVectorRM. Install it with pip install dspy-ai[pgvector]
```

Pip install fails both for dspy and dspy-ai:

```
pip install dspy-ai[pgvector]
Requirement already satisfied: dspy-ai[pgvector] in /home/wsl/micromamba/envs/GenQA/lib/python3.11/site-packages (2.5.3)
WARNING: dspy-ai 2.5.3 does not provide the extra 'pgvector'
```
```
pip install dspy[pgvector]
Requirement already satisfied: dspy[pgvector] in /home/wsl/micromamba/envs/GenQA/lib/python3.11/site-packages (2.5.6)
WARNING: dspy 2.5.6 does not provide the extra 'pgvector'
```

**Comment by okhat** [comment]
Thanks @excubo-jg ! Was this working for your before 2.5.6? Or is it the first time you're trying this?

Could you try:
```python
pip install pgvector psycopg2-binary
```

Then do your import. I think that's what it needs. We should edit the error message to ask people to install these there.

**Comment by arnavsinghvi11** [comment]
Hi @excubo-jg , does #1608 resolve this? turns out that `dspy-ai[pgvector]` was never supported!

Feel free to test on the branch and lmk if any other changes are needed (as I don't have access to pgvector related functionality to test)
