### ISSUE TITLE
dataloaders test_size=0

### ISSUE THREAD

**Issue by cognitivetech** [stanfordnlp/dspy#426]
Trying to duplicate an example from [dataloaders](https://github.com/stanfordnlp/dspy/blob/main/examples/dataloaders/dataloaders_dolly.ipynb) https://github.com/stanfordnlp/dspy/pull/379 

```python
import dspy
from dspy.datasets import DataLoader

dl = DataLoader(
    train_size = 1.0,
)

notes_data = dl.from_csv(
    "dolly_subset_100_rows.csv",
    fields=["instruction","context","response"],
)

print(f"Keys present in the returned dict: {list(notes_data.keys())}")
print(f"Number of examples in train set: {len(notes_data['train'])}")
```

gives me this response:

```bash
Downloading data files: 100%|███████████████████████████| 1/1 [00:00<00:00, 17119.61it/s]
Extracting data files: 100%|█████████████████████████████| 1/1 [00:00<00:00, 2078.45it/s]
Generating train split: 100 examples [00:00, 5305.35 examples/s]
Traceback (most recent call last):
  File "/home/asimov/github/dspy/sample.py", line 8, in <module>
    notes_data = dl.from_csv(
                 ^^^^^^^^^^^^
  File "/home/asimov/anaconda3/envs/dspy/lib/python3.11/site-packages/dspy/datasets/dataloader.py", line 87, in from_csv
    self._process_dataset(dataset, fields)
  File "/home/asimov/anaconda3/envs/dspy/lib/python3.11/site-packages/dspy/datasets/dataloader.py", line 23, in _process_dataset
    tmp_dataset = dataset.train_test_split(test_size=(dev_split_size+test_split_size))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asimov/anaconda3/envs/dspy/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asimov/anaconda3/envs/dspy/lib/python3.11/site-packages/datasets/fingerprint.py", line 511, in wrapper
    out = func(dataset, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asimov/anaconda3/envs/dspy/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 4392, in train_test_split
    raise ValueError(
ValueError: test_size=0 should be either positive and smaller than the number of samples 100 or a float in the (0, 1) range
```

**Comment by okhat** [comment]
Thanks for opening the issue! Let me cc  @krypticmouse

**Comment by krypticmouse** [comment]
Updating that notebook today that was an older API for dataloader!

**Comment by krypticmouse** [comment]
@cognitivetech Updated the docs you can have a look!

https://github.com/stanfordnlp/dspy/blob/main/examples/dataloaders/dataloaders_dolly.ipynb
