### ISSUE TITLE
Cannot call `module.save()` after compilation if TypedPredictor in Module

### ISSUE THREAD

**Issue by Mikkolehtimaki** [stanfordnlp/dspy#549]
Trying to save optimization results using the `save()` method will crash on `TypeError: <PydanticObject> is not JSON serializable`.

**Comment by insop** [comment]
I believe this issue was fixed recently.
I am using this code (244a81705f1bb84eb3ccff24c2d18aa539fa1aa1) and load/save works. You might want to catch up to the latest and check.

**Comment by eulervoid** [comment]
I'm running into the same issue.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File ".../optimize.py", line 33, in <module>
    optimized_predictor.save("basic_story_gen.json")
  File ".../.venv/lib/python3.11/site-packages/dspy/primitives/module.py", line 75, in save
    f.write(ujson.dumps(self.dump_state(), indent=2))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: <PydanticObject> is not JSON serializable
```
