### ISSUE TITLE
Pickle error when trying to compile module that contains ChromadbRM

### ISSUE THREAD

**Issue by lakshmanok** [stanfordnlp/dspy#575]
When I try to use teleprompter with a dspy Module that contains a ChromadbRM, I get a Pickle error.

This is my Module:
```
class MyRAG(dspy.Module):
    def __init__(self):
        super().__init__()
        from chromadb.utils import embedding_functions
        default_ef = embedding_functions.DefaultEmbeddingFunction()
        self.prog = ChromadbRM(CHROMA_COLLECTION_NAME, CHROMADB_DIR, default_ef, k=3)

    def forward(self, question):
        return self.prog(question)
```
and this is how I'm using teleprompt:
```
    trainset = [dspy.Example(question=e['question'], answer=e['answer']) for e in traindata]
    teleprompter = teleprompt.LabeledFewShot()
    optimized_rag = teleprompter.compile(student=MyRAG(), trainset=trainset)
```
and this is the error:
```
Traceback (most recent call last):
  
    optimized_rag = teleprompter.compile(student=MyRAG(), trainset=trainset)
  File "/opt/conda/lib/python3.10/site-packages/dspy/teleprompt/vanilla.py", line 11, in compile
    self.student = student.reset_copy()
  File "/opt/conda/lib/python3.10/site-packages/dspy/primitives/module.py", line 51, in reset_copy
    obj = copy.deepcopy(self)
...
File "/opt/conda/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/conda/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'sqlite3.Connection' object
```
What am I missing?

**Comment by okhat** [comment]
Hey, the issue is that ChromadbRM has sqlite3.Connection, which can't be pickled.

What are you trying to achieve? This can't do RAG since you don't have any modules that use the LM to generate answers.

**Comment by lakshmanok** [comment]
yes, I was using an instance of this class to fill out the context of another Module which has multiple inputs.  
```
class Advisor(dspy.Module):
    def __init__(self):
        super().__init__()
        ...
        self.bidding_system = MyRAG()
        ...
        self.prog = dspy.ChainOfThought(AdvisorSignature, n=3)

    def forward(self, question):
        ...
        input_c = self.bidding_system(question)
        ...
        prediction = self.prog(input_a=..., input_b=..., input_c=input_c, question=question)
        return prediction.answer
```
I'll change it to be just a function.

**Comment by okhat** [comment]
Ah got it, thanks a lot. Let us know if that fixes it
